CosplayBlogBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: CosplayBlogBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: 255
        user:
            type: string
            length: 255
    lifecycleCallbacks: {  }
