desguize_homepage:
    path:     /
    defaults: { _controller: DesguizeBundle:Default:index }

desguize_cgu:
    path:     /cgu
    defaults: { _controller: DesguizeBundle:Default:cgu }

desguize_contact:
    path:     /contact
    defaults: { _controller: DesguizeBundle:Default:contact }