services:
    desUser.form.registration:
        class: DesguizeBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: des_user_registration }

    desUser.form.profile:
        class: DesguizeBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: des_user_profile }